### ISSUE TITLE
TypeError: get_product_historic_rates() got an unexpected keyword argument 'product'

### ISSUE THREAD

**Issue by CoolSpot** [nitrocode/CoinTaxes#2]
Ubuntu 16.04 LTS, python 2.7, ConTaxes' latest master:

Traceback (most recent call last):
  File "CoinTaxes.py", line 158, in <module>
    main()
  File "CoinTaxes.py", line 112, in main
    exchange_buys, exchange_sells = fix_orders(exchange, exchange_buys, exchange_sells)
  File "CoinTaxes.py", line 40, in fix_orders
    price_usd = exchange.get_price(order['order_time'], product='BTC-USD')
  File "/home/ivan/Documents/code/CoinTaxes/exchanges/gdax_reader.py", line 125, in get_price
    end=order_time
TypeError: get_product_historic_rates() got an unexpected keyword argument 'product'

**Comment by CoolSpot** [comment]
This error caused by argument name change for get_product_historic_rates()  from 
"product" to "product_id".

**Comment by nitrocode** [comment]
I just updated the `master` branch. It had fallen behind because I was making changes in the branch `Cleaning`. I don't see this issue locally.

**Comment by CoolSpot** [comment]
It seems that the branch "Cleaning" is not on the github. It is probably as intended, just FYI.

**Comment by nitrocode** [comment]
I removed the defunct branch just in case. Thank you!

**Comment by nitrocode** [comment]
@CoolSpot I just updated the code again. Is this still an issue?

**Comment by CoolSpot** [comment]
It is.
