### ISSUE TITLE
NameError: global name 'sell_index' is not defined

### ISSUE THREAD

**Issue by CoolSpot** [nitrocode/CoinTaxes#4]
After fixing #2 and #3 :

Connected to Coinbase.
Sorting the buy and sell orders by time
Traceback (most recent call last):
  File "CoinTaxes.py", line 197, in <module>
    main()
  File "CoinTaxes.py", line 182, in main
    tax_year=config['year']
  File "/home/ivan/Documents/code/CoinTaxes/formats/fill_8949.py", line 70, in get_cost_basis
    print("WARNING! COULD NOT FIND A COST BASIS FOR sell_index=%d!" % sell_index)
NameError: global name 'sell_index' is not defined

It looks like variable "sell_index" was eliminated during refactoring.

**Comment by nitrocode** [comment]
I've been working on this as a side project to get my taxes in before the April 2017 deadline. I'll work on this more this week and resolve the refactoring issues. I'm surprised I didn't run into this before sending. Perhaps I missed a few commits when I pushed up.

Thanks for adding these issues! Please feel free to add more or send a PR.

**Comment by CoolSpot** [comment]
Will do PR for all three issues soon.

**Comment by nitrocode** [comment]
Ah I see the issue you are facing now. I did this in pypy 2.7 and you must be using python 3 which was my next TODO task.

**Comment by CoolSpot** [comment]
Not sure what you mean, but I use Python 2.7 to run the CoinTaxes.py .
My tree is:
```
commit bd40e23697617ed56c5ef144736f5399da6d9cca
Author: nitrocode <nitrocode@users.noreply.github.com>
Date:   Sun Apr 15 23:34:17 2018 -0400

```

**Comment by nitrocode** [comment]
Interesting. I'll have to look more into this. For now, I don't want to support python 2 anymore as it will become deprecated in roughly [20 more months](https://pythonclock.org). I pushed a change today to allow `pipenv` to work easily with the app and removed `requirements.txt` to discourage the use of `pip`.

**Comment by nitrocode** [comment]
Is this still an issue? You never sent the PRs :stuck_out_tongue:
