### ISSUE TITLE
Generates invalid TXF file

### ISSUE THREAD

**Issue by CoolSpot** [nitrocode/CoinTaxes#5]
This is result TXF file:
```
V042
ACyrptoTaxes
D 04/16/2018
^
TD
N712
C1
L1
$1.55131499 ETH
D06/14/2017
D06/28/2017
$613.54
$453.70
^
```

TurboTax 2017 doesn't accept it as correct. According to [specification](https://turbotax.intuit.com/txf/TXF042.jsp) line "$1.55131499 ETH" must be "P 1.55131499 ETH" instead.

**Comment by nitrocode** [comment]
Good catch! I'll have to read up more on this specification. 

Just a note, a lot of the code has been derived from [CryptoTaxes](https://github.com/gsugar87/CryptoTaxes) and there is a lot to do so any PRs would be appreciated!
